export const UPDATE_DISPLAY_CATEGORY = "UPDATE_DISPLAY_CATEGORY";
export const SELECTED_PRODUCT_DETAILS = "SELECTED_PRODUCT_DETAILS";
export const CATEGORY_PRODUCTS = "CATEGORY_PRODUCTS";
export const FAVORITE_PRODUCTS = "FAVORITE_PRODUCTS";

